Понял, давайте попробуем другую конфигурацию для установки Yarn. Вот обновленный конфигурационный файл GitHub Actions с использованием другого способа установки Yarn:

  ```yaml
# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node and Yarn
        run: |
          curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.22
          export PATH=$HOME/.yarn/bin:$PATH
          yarn --version
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
  ```
  
  Этот обновленный файл GitHub Actions использует установку Yarn через curl и bash, а затем выполняет установку зависимостей и сборку проекта с помощью Yarn. Пожалуйста, попробуйте эту конфигурацию и проверьте, будет ли она работать для вашего проекта.
